### ISSUE TITLE
我的服务页面，提示没找到该患者

### ISSUE THREAD

**Issue by ilaipi** [lingdou/daoqun-hcp-ios#4]
![image](https://user-images.githubusercontent.com/1689135/53073027-dd081c80-3521-11e9-8f2c-5795728811a8.png)

**Comment by ilaipi** [comment]
貌似后端报的错误

**Comment by ilaipi** [comment]
```
15:10:38.273 DEBUG daoqun-backend:
    Mongoose: hcpconsumers.findOne({
      "status": "live",
      "consumer": "5c6cd6443d50611ee06efd3b",
      "hcp": "5c6bc01d704519258c573608"
    }, {
      "fields": {}
    })
15:10:38.274 ERROR daoqun-backend: 处理请求出现异常
    InternalServerError: 没找到该患者！
        at Object.throw (/home/dev/daoqun-backend/node_modules/koa/lib/context.js:97:11)
        at getConsumerDetail (/home/dev/daoqun-backend/src/modules/hcpConsumer/controller.js:21:5)
        at <anonymous>
```

**Comment by ilaipi** [comment]
可能是App端代码问题，更新最新代码后ok。

最早的时候后端发给前端的数据id错误
